/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cse310_assingment;

import com.mysql.cj.protocol.Resultset;
import javax.swing.JOptionPane;
import javax.swing.*;
import java.sql.*;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP-NPC
 */
public class Sectionselect extends javax.swing.JFrame {
     
    String Passedinfo;
   
    public Sectionselect(String u) {
        
         Passedinfo = u;
        initComponents();
       user_show();
    }
    
    
    public ArrayList <User> userList(){
     ArrayList <User> userList = new ArrayList<>();
      try {
           Class.forName("com.mysql.cj.jdbc.Driver");
           java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","Harrypotter7");
           String qr = "select * from secinfo";
           Statement st = con.createStatement();
           ResultSet rs = st.executeQuery(qr);
           User user;
           while (rs.next()){
            user = new User (rs.getInt("secone"),rs.getInt("sectwo"));
           userList.add(user);
        
                             }
           }
      catch (Exception e ){
            JOptionPane.showMessageDialog(null,"Updated");
        }
     
       return userList;

}
    public  void user_show() {
     ArrayList <User> list = userList();
     DefaultTableModel model = (DefaultTableModel)seats.getModel();
     Object[] row = new Object[2];
     for (int i = 0 ; i<list.size();i++){
         row[0] = list.get(i).getsecone();
         row[1] = list.get(i).getsectwo();
         model.addRow(row);
     }
}
    
   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        sec = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        confirm = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        seats = new javax.swing.JTable();

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Section Selection ");

        jLabel2.setText("Please select the section most convinient to you");

        jLabel3.setText("Sectiom - 1");

        jLabel4.setText("Sunday");

        jLabel5.setText("4:00 pm to 5:30 pm");

        jLabel6.setText("Seats Remaining :");

        sec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Section 1", "Section 2" }));
        sec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                secActionPerformed(evt);
            }
        });

        jLabel7.setText("Section 2");

        jLabel8.setText("Monday");

        jLabel9.setText("1:00 pm to 2:30 pm");

        confirm.setText("Confirm");
        confirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmActionPerformed(evt);
            }
        });

        seats.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        seats.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Section 1", "Section 2"
            }
        ));
        jScrollPane1.setViewportView(seats);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(87, 87, 87)
                .addComponent(confirm)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(322, 322, 322)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel8))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(33, 33, 33)
                                .addComponent(jLabel4)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9))
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(119, 119, 119))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirm))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void secActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_secActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_secActionPerformed

    private void confirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmActionPerformed

        try {
        Class.forName("com.mysql.cj.jdbc.Driver");
           java.sql.Connection con1 = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","Harrypotter7");
            int sectorone = 6;
            int sectortwo = 6
             ;
           String qr = "select secone from secinfo" ;
           String qr2 ="select sectwo from secinfo";
           Statement st2 =con1.createStatement();
           Statement st = con1.createStatement();
           ResultSet rs2 = st2.executeQuery(qr2);
           ResultSet rs = st.executeQuery(qr);
           while (rs.next()){
            sectorone = rs.getInt("secone");
           }
           while (rs2.next()){
           sectortwo = rs2.getInt("sectwo");
           
           }
           
          
          
         // int sectortwo = rs.getInt("sectwo");
       String selection ;
       selection = sec.getSelectedItem().toString();
     //  while (rs.next()){
       //    User usertwo = new User(rs.getInt("secone"),rs.getInt("sectwo"));
         // }
       if (selection.equals("Section 1") && sectorone > 0  ){
           
            try {
              
           Class.forName("com.mysql.cj.jdbc.Driver");
           java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","Harrypotter7");
           String query = "UPDATE secinfo SET secone = secone - 1 ";
           String secquery = "UPDATE students SET Section = 1 WHERE Email = ? ";
           PreparedStatement pst2 = con.prepareStatement(secquery);
           PreparedStatement pst = con.prepareStatement(query);
           pst2.setString(1, Passedinfo);
           pst.executeUpdate();
           pst2.executeUpdate();
             JOptionPane.showMessageDialog(null,"Updated");
             GUI up = new GUI();
             up.setVisible(true);
             super.dispose();
       
            }
            catch (Exception e ){
            JOptionPane.showMessageDialog(null,e);
        }
       
       }
       else if (selection.equals("Section 2") && sectortwo > 0 ){
        try {
           Class.forName("com.mysql.cj.jdbc.Driver");
           java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/studentinfo","root","Harrypotter7");
           String query = "UPDATE secinfo SET sectwo = sectwo - 1 ";
           String secquery = "UPDATE students SET Section = 2 WHERE Email = ? ";
           PreparedStatement pst2 = con.prepareStatement(secquery);
           PreparedStatement pst = con.prepareStatement(query);
           pst2.setString(1, Passedinfo);
           pst.executeUpdate();
           pst2.executeUpdate();
             JOptionPane.showMessageDialog(null,"Updated");
             GUI up = new GUI();
             up.setVisible(true);
             super.dispose();
       
            }
            catch (Exception e ){
            JOptionPane.showMessageDialog(null,"error here2");
        }
       
       
       
       
       }
       
       else {
       JOptionPane.showMessageDialog(null,"No seats remaining in that section , please try and select another section  or contact your faculty");
       
       }
       
       
    // over all try closer
    }
catch (Exception e ){
            JOptionPane.showMessageDialog(null,e);
}

//method closer
    }//GEN-LAST:event_confirmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sectionselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sectionselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sectionselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sectionselect.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new Sectionselect().setVisible(true);
                 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirm;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable seats;
    private javax.swing.JComboBox<String> sec;
    // End of variables declaration//GEN-END:variables
}
